name: DevSecOps Pipeline (EKS)

on:
  push:
    branches: [ main ]

jobs:

  # 🔍 JOB 1 — Scan code Python
  sast-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run Bandit
      run: |
        pip install bandit
        pip install -r app/requirements.txt
        bandit -r app/ --severity-level high

  # 🐳 JOB 2 — Scan Docker
  docker-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Image
      run: docker build -t app-test -f docker/Dockerfile .

    - name: Scan with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'app-test'
        severity: 'CRITICAL,HIGH'
        exit-code: '0'

  # 🏗️ JOB 3 — Scan Terraform
  iac-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run Checkov
      run: |
        pip install checkov
        checkov -d terraform/ --quiet || true

  # 🚀 JOB 4 — (Simulation Deploy Kubernetes)
  deploy:
    needs: [sast-scan, docker-scan, iac-scan]
    runs-on: ubuntu-latest

    steps:
    - name: Deploy message
      run: echo "✅ Ready for Kubernetes deployment (EKS)"
